// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonsApi.Data;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240322014619_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPI.Models.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ViagemCaronaOfertaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ViagemCaronaOfertaId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("WebAPI.Models.ViagemCaronaOferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HoraSaida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroVagas")
                        .HasColumnType("int");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rota")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ViagensCaronaOferta");
                });

            modelBuilder.Entity("WebAPI.Models.Usuario", b =>
                {
                    b.HasOne("WebAPI.Models.ViagemCaronaOferta", null)
                        .WithMany("Passageiros")
                        .HasForeignKey("ViagemCaronaOfertaId");
                });

            modelBuilder.Entity("WebAPI.Models.ViagemCaronaOferta", b =>
                {
                    b.Navigation("Passageiros");
                });
#pragma warning restore 612, 618
        }
    }
}
